### PR TITLE
WIP: feat: show page property in list

### PR DESCRIPTION
**Pull request by congjiujiu**
截屏2022-09-20 14 31 06

### CODE REVIEW

**Comment by lizimeow** [comment]
如果图标不加灰色背景，然后这个框的 padding 稍微大一点呢？圆角也大一点，考虑加点颜色。

**Comment by forehalo** [comment]
Is it better to move all problematic pages to the last?

**Comment by forehalo** [comment]
image
what's the difference of this two?

**Comment by lizimeow** [comment]
> image what's the difference of this two?

It may be disabled. 

And the "desktop" icon doesn't looks like it matches the page.

**Comment by congjiujiu** [comment]
> > image what's the difference of this two?
> 
> It may be disabled.
> 
> And the "desktop" icon doesn't looks like it matches the page.

yes...the gray one means it's disabled. And the different icon means it is a competitor page. I am still thinking about the styles cause I feel they are some like ugly now.

**Comment by lizimeow** [comment]
Please check the code again after #82 is merged.

**Comment by lizimeow** [comment]
What does it look like when user has more than 3 profiles associated with one page.

**Comment by lizimeow** [comment]
i feel like card looks better than list...😂

**Comment by lizimeow** [comment]
> Is it better to move all problematic pages to the last?

i think so too.

**Comment by lizimeow** [comment]
it's all in #162 .

**Pull request closed without merging**
