### PR TITLE
fix: homepage loading twinkle

### PR DESCRIPTION
**Pull request by congjiujiu**
Still have some twinkle between loading and empty state.

### CODE REVIEW

**Comment by forehalo** [comment]
what's the necessity of sending api requests in layout effect?

**Comment by congjiujiu** [comment]
> what's the necessity of sending api requests in layout effect?

set the `loading` state as early as possible.

in some cases, the `loading` maybe like `false -> true -> false` so it will cause `empty -> loading -> empty`.

**Comment by forehalo** [comment]
> > what's the necessity of sending api requests in layout effect?
> 
> set the `loading` state as early as possible.
> 
> in some cases, the `loading` maybe like `false -> true -> false` so it will cause `empty -> loading -> empty`.

Why not set the default loading property to `true`

**Comment by congjiujiu** [comment]
> > > what's the necessity of sending api requests in layout effect?
> > 
> > 
> > set the `loading` state as early as possible.
> > in some cases, the `loading` maybe like `false -> true -> false` so it will cause `empty -> loading -> empty`.
> 
> Why not set the default loading property `true`? BTW, layout effects are triggered after effects

You are right. I will change the initial loading to true and remove the layout effects.

**Review by EYHN — APPROVED** [review]
LGTM

**Review by lizimeow — APPROVED** [review]

**Pull request merged**
